name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Greetings, thank you for your first contribution / interaction with the Publications Documentation feel free to look around the REPO in the meantime whilst your issue is resolved.'
        pr-message: 'Greetings'
